---
--- Generated by Luanalysis
--- Created by 13467.
--- DateTime: 2024/10/22 16:04
---

---秒杀优惠券脚本
local voucherID=ARGV[1] ---秒杀券ID
local userID=ARGV[2] ---用户ID

local stockKey='seckill:stock:'.. voucherID
local orderKey='seckill:order:'..voucherID

if(tonumber(redis.call('get',stockKey))<=0) then
    return 1 ---库存不足，返回1
end

if(redis.call('sismember',orderKey,userID)==1) then
    return 2 ---用户订单已存在，说明重复下单，返回2
end

---减库存
redis.call("incrby",stockKey,-1)

---将用户订单存入redis
redis.call("sadd",orderKey,userID)

---成功返回0
return 0
